apiVersion: v1
kind: Service
metadata:
  name: hari-demo
spec:
  type: LoadBalancer
  ports:
  - port: 1234
    targetPort: 1234
    protocol: TCP
    name: http
  selector:
    app: hari-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hari-demo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hari-demo
  template:
    metadata:
      labels:
        app: hari-demo
        version: hari-demo-version-1
    spec:
      containers:
      - name: hari-demo-1
        image: janardhan54/haridemo:1
        imagePullPolicy: Always
        env:
           - name: TZ
             value: Asia/Kolkata